version: '3.8'

name: ai_aigod

services:
  aigod:
    build:
      context: .
      dockerfile: Dockerfile
    image: registry.bkholding.vn/ai.aigod.app:${TAG:-0.1.3}
    container_name: ai_aigod_app
    ports:
      - "${PORT:-21020}:8000"
    env_file: .env
    environment:
      - PORT=8000
      - HOST=0.0.0.0
    restart: unless-stopped
